// <auto-generated />
using System;
using Actividad4LengPro3.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad4LengPro3.Migrations
{
    [DbContext(typeof(Actividad4DbContext))]
    [Migration("20250708132215_CalificacionesTabla")]
    partial class CalificacionesTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad4LengPro3.Models.CalificacionViewModel", b =>
                {
                    b.Property<string>("MatriculaEstudiante")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CodigoMateria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("MatriculaEstudiante", "CodigoMateria", "Periodo");

                    b.HasIndex("CodigoMateria");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Actividad4LengPro3.Models.EstudiantesViewModel", b =>
                {
                    b.Property<string>("Matricula")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaBecado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PorcentajeBeca")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TerminosYCondiciones")
                        .HasColumnType("bit");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Actividad4LengPro3.Models.MateriaViewModel", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Actividad4LengPro3.Models.CalificacionViewModel", b =>
                {
                    b.HasOne("Actividad4LengPro3.Models.MateriaViewModel", "Materia")
                        .WithMany()
                        .HasForeignKey("CodigoMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Actividad4LengPro3.Models.EstudiantesViewModel", "Estudiante")
                        .WithMany()
                        .HasForeignKey("MatriculaEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });
#pragma warning restore 612, 618
        }
    }
}
